export const PRINTING_ERROR_CODES = {
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  PRINTER_OFFLINE: 'PRINTER_OFFLINE',
  CONFIG_INVALID: 'CONFIG_INVALID',
  TEMPLATE_INVALID: 'TEMPLATE_INVALID',
  TEMPLATE_VERSION_CONFLICT: 'RECEIPT_TEMPLATE_VERSION_CONFLICT',
  CHANNEL_NOT_IMPLEMENTED: 'CHANNEL_NOT_IMPLEMENTED',
  LEASE_EXPIRED: 'LEASE_EXPIRED',
  PRINT_OUTCOME_UNKNOWN: 'PRINT_OUTCOME_UNKNOWN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNKNOWN: 'UNKNOWN',
  RESOURCE_NOT_FOUND: 'PRINTING_RESOURCE_NOT_FOUND',
  PRINTER_DISABLED: 'PRINTER_DISABLED',
  STATE_CONFLICT: 'PRINT_JOB_STATE_CONFLICT',
  TASK_CENTER_DISABLED: 'PRINTING_TASK_CENTER_DISABLED',
  AUTO_CREATE_DISABLED: 'PRINTING_AUTO_CREATE_DISABLED',
  EXECUTION_DISABLED: 'PRINTING_EXECUTION_DISABLED',
  LEGACY_PRINTING_DISABLED: 'LEGACY_PRINTING_DISABLED',
  DUAL_PATH_NOT_ALLOWED: 'PRINTING_DUAL_PATH_NOT_ALLOWED',
  TERMINAL_AUTH_NOT_CONFIGURED: 'TERMINAL_AUTH_NOT_CONFIGURED',
  TERMINAL_AUTH_INVALID: 'TERMINAL_AUTH_INVALID',
  TERMINAL_PAIRING_REJECTED: 'TERMINAL_PAIRING_REJECTED',
  TERMINAL_DEVICE_CONFLICT: 'TERMINAL_DEVICE_CONFLICT',
  TERMINAL_DISABLED: 'TERMINAL_DISABLED',
  PRINTING_NOT_ENABLED: 'PRINTING_NOT_ENABLED',
  CONTENT_HASH_MISMATCH: 'PRINT_CONTENT_HASH_MISMATCH',
  TERMINAL_UPGRADE_REQUIRED: 'CLIENT_UPGRADE_REQUIRED',
  CANONICAL_PAYLOAD_REQUIRED: 'CANONICAL_PRINT_PAYLOAD_REQUIRED',
  PAYLOAD_LENGTH_MISMATCH: 'PAYLOAD_LENGTH_MISMATCH',
  PAYLOAD_SHA_MISMATCH: 'PAYLOAD_SHA_MISMATCH',
  PRINT_ARTIFACT_ABNORMAL_SIZE: 'PRINT_ARTIFACT_ABNORMAL_SIZE',
  USB_PERMISSION_DENIED: 'USB_PERMISSION_DENIED',
  USB_DEVICE_DETACHED: 'USB_DEVICE_DETACHED',
  USB_INTERFACE_CLAIM_FAILED: 'USB_INTERFACE_CLAIM_FAILED',
  USB_WRITE_FAILED: 'USB_WRITE_FAILED',
  CLOUD_PROVIDER_NOT_CONFIGURED: 'CLOUD_PROVIDER_NOT_CONFIGURED',
  CLOUD_CREDENTIALS_INVALID: 'CLOUD_CREDENTIALS_INVALID',
  CLOUD_DEVICE_INVALID: 'CLOUD_DEVICE_INVALID',
  CLOUD_PROVIDER_REJECTED: 'CLOUD_PROVIDER_REJECTED',
  CLOUD_PROVIDER_UNAVAILABLE: 'CLOUD_PROVIDER_UNAVAILABLE',
  CLOUD_RESULT_PENDING: 'CLOUD_RESULT_PENDING',
  CLOUD_TASK_CANCELLED: 'CLOUD_TASK_CANCELLED',
  LAN_PRINTING_DISABLED: 'LAN_PRINTING_DISABLED',
  LAN_BINDING_MISSING: 'LAN_BINDING_MISSING',
  TERMINAL_OFFLINE: 'TERMINAL_OFFLINE',
  CONNECTOR_SERVICE_STOPPED: 'CONNECTOR_SERVICE_STOPPED',
  TEST_PRINT_REQUIRED: 'TEST_PRINT_REQUIRED',
  PRINTER_HAS_ACTIVE_JOBS: 'PRINTER_HAS_ACTIVE_JOBS',
  PRINTER_PRINTING_IN_PROGRESS: 'PRINTER_PRINTING_IN_PROGRESS',
  PRINTER_ARCHIVED_READD_REQUIRED: 'PRINTER_ARCHIVED_READD_REQUIRED',
} as const;

export type PrintingErrorCode =
  (typeof PRINTING_ERROR_CODES)[keyof typeof PRINTING_ERROR_CODES];

export function containsPrintingCredentialMaterial(value: string) {
  return (
    /\byt1\.[1-9][0-9]{0,18}\.[A-Za-z0-9_-]{43}\b/i.test(value) ||
    /\bBearer\s+[^\s,;]+/i.test(value) ||
    /\beyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/.test(value)
  );
}

export function sanitizePrintingError(message: string | null | undefined) {
  if (!message) return null;
  return message
    .replace(
      /\byt1\.[1-9][0-9]{0,18}\.[A-Za-z0-9_-]{43}\b/gi,
      '[redacted-terminal-credential]',
    )
    .replace(/\bBearer\s+[^\s,;]+/gi, 'Bearer [redacted]')
    .replace(
      /\beyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/g,
      '[redacted-jwt]',
    )
    .replace(
      /(token|password|secret|cookie|authorization|credential|api[_-]?key)\s*[:=]\s*[^\s,;]+/gi,
      '$1=[redacted]',
    )
    .replace(/\b\d{8,15}\b/g, '[redacted-number]')
    .slice(0, 300);
}
