import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const page = await readFile(new URL('../src/pages/ProductsPage.vue',import.meta.url),'utf8');
const css = await readFile(new URL('../src/styles/merchant-pages.css',import.meta.url),'utf8');
const shellCss = await readFile(new URL('../src/styles/merchant-workbench.css',import.meta.url),'utf8');
for(const marker of ['mx-catalog-layout','mx-catalog-rail','mx-catalog-table','mx-mobile-catalog','mx-mobile-product','mx-category-directory','mx-product-profile','mx-product-editor'])assert(page.includes(marker),marker);
for(const marker of ['m-product-category-add','openCreateCategoryWorkspace','mx-product-fab'])assert(page.includes(marker),marker);
assert(page.includes('v-else-if="!isMobileProductList" class="mx-catalog-table-wrap"'),'desktop table conditional');
assert(page.includes('v-else class="mx-mobile-catalog"'),'phone uses separate product tree');
assert(page.includes("window.matchMedia('(max-width: 768px)')"),'shared breakpoint');
assert(page.includes('loading="lazy" decoding="async"'),'lazy images');
assert(page.includes('product.menuThumbnailUrl?.trim()'),'thumbnail preference');
assert(page.includes('failedListImageUrls'),'failed thumbnail and original fallback');
assert(page.includes('failedPreviewUrl'),'broken editor preview fallback');
assert(page.includes('productForm.imageUrl ? resolveMediaUrl(productForm.imageUrl)'),'editor keeps original');
assert(shellCss.includes('table-layout: fixed'),'real table layout');
assert(css.includes('grid-template-columns: 214px minmax(0,1fr)'),'root grid shrinks');
assert(css.includes('col.actions-column { width: 104px; }')&&css.includes('col.actions-column { width: 92px; }'),'desktop and tablet action allocation');
assert(css.includes('text-overflow: ellipsis'),'bounded multilingual fields');
assert(css.includes('.mx-module-tabs--mobile-hidden'),'phone menu does not repeat the desktop module switcher');
assert(css.includes('bottom: calc(var(--m-bottom-nav-h) + env(safe-area-inset-bottom) + 18px)'),'dish add action clears the PWA bottom navigation and safe area');
assert(page.includes(':title="productName(row)"'),'full localized dish tooltip');
assert(page.includes(':title="categoryName(row.category)"'),'full category tooltip');
for(const label of ['edit','delete'])assert(page.includes("{{ t('"+label+"') }}"),label+' remains visible');
assert(page.includes('unit: productForm.unit.trim() || null'),'unit payload unchanged');
assert(page.includes('v-model="productForm.unit"'),'unit field');
assert(page.includes("t('productUnitPlaceholder')"),'unit localized placeholder');
assert(page.includes('maxlength="32"'),'unit max length');
assert(page.includes('v-if="row.unit?.trim()"'),'blank unit suppressed');
assert(page.includes('@submit.prevent="saveProduct"'),'existing submit handler');
assert(page.includes('role="alertdialog"'),'destructive confirmation remains');
console.log('menu management UI checks passed');
