import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dictionary = fs.readFileSync(path.join(root, 'src/pages/PlatformPromotionTagsPage.vue'), 'utf8');
const detail = fs.readFileSync(path.join(root, 'src/pages/PlatformMerchantDetailPage.vue'), 'utf8');
const list = fs.readFileSync(path.join(root, 'src/pages/PlatformMerchantsPage.vue'), 'utf8');

assert.match(dictionary, /scope: 'OPERATIONAL'/);
assert.match(dictionary, /value: 'CUISINE'/);
assert.match(dictionary, /value: 'SCENE'/);
assert.match(dictionary, /标签字典管理/);
assert.match(dictionary, /messageIsSuccess/);
assert.match(dictionary, /aria-live="polite"/);
assert.match(dictionary, /平台运营不进入商家详情/);

assert.match(detail, /tag\.scope === 'OPERATIONAL'/);
assert.match(detail, /tag\.scope === 'CUISINE'/);
assert.match(detail, /tag\.scope === 'SCENE'/);
assert.match(detail, /平台运营标签/);
assert.match(detail, /详情页展示标签/);
assert.match(detail, /用于平台运营\/首页逻辑，不直接显示在商家详情页/);
assert.match(detail, /updatePlatformMerchantTags\(merchantId\.value, \[\.\.\.selectedTagIds\.value\]\)/);
assert.match(detail, /title: '门店外观 STORE'/);
assert.match(detail, /title: '菜品 PRODUCT'/);
assert.match(detail, /title: '用餐环境 ENVIRONMENT'/);
assert.match(detail, /title: '菜单 MENU'/);
assert.match(detail, /小程序顶部图库：门店外观/);
assert.match(detail, /小程序顶部图库：菜品/);
assert.match(detail, /小程序顶部图库：用餐环境/);
assert.match(detail, /当前已认领商家 V3\.2 顶部图库不展示 MENU/);
assert.match(detail, /displayLimit: 3,[\s\S]*displayLimit: 6,[\s\S]*displayLimit: 3,/);
assert.match(detail, /const contentImageSections = computed/);
assert.match(detail, /visibleCount > section\.displayLimit/);
assert.match(detail, /frontendImagePositions/);
assert.match(detail, /前台第 \$\{section\.frontendImagePositions\[image\.id\]\} 张/);
assert.match(detail, /超出顶部图库展示上限/);
assert.match(detail, /v-for="section in contentImageSections"/);
assert.match(detail, /openImagePicker\(section\.type\)/);
assert.match(detail, /v-model\.number="image\.sortOrder"/);
assert.match(detail, /v-model="image\.isVisible"/);
assert.match(detail, /hideMerchantImage\(image\)/);
assert.match(detail, /selectedCuisineTags/);
assert.match(detail, /selectedSceneTags/);
assert.match(detail, /frontendDetailTagIds/);
assert.match(detail, /超出前台上限/);
assert.match(detail, /messageIsSuccess/);
assert.match(detail, /aria-live="polite"/);
assert.doesNotMatch(detail, /<h3>内容图库<\/h3>/);
assert.match(list, /item\.enabled && item\.scope === 'OPERATIONAL'/);

console.log('promotion-tag-scope-ui: source assertions passed.');
