import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dictionary = fs.readFileSync(path.join(root, 'src/pages/PlatformPromotionTagsPage.vue'), 'utf8');
const detail = fs.readFileSync(path.join(root, 'src/pages/PlatformMerchantDetailPage.vue'), 'utf8');
const list = fs.readFileSync(path.join(root, 'src/pages/PlatformMerchantsPage.vue'), 'utf8');
const api = fs.readFileSync(path.join(root, 'src/api/platform.ts'), 'utf8');

assert.match(dictionary, /scope: 'OPERATIONAL'/);
assert.match(dictionary, /value: 'CUISINE'/);
assert.match(dictionary, /value: 'SCENE'/);
assert.match(dictionary, /标签字典管理/);
assert.match(dictionary, /messageIsSuccess/);
assert.match(dictionary, /aria-live="polite"/);
assert.match(dictionary, /const tagGroups = computed/);
assert.match(dictionary, /item\.merchantReferenceCount > 0/);
assert.match(dictionary, /item\.reserved/);
assert.match(dictionary, /该标签当前被 \$\{item\.merchantReferenceCount\} 个商家使用/);
assert.match(dictionary, /请再次确认永久删除/);
assert.match(dictionary, /确认删除该标签吗/);
assert.match(dictionary, /deletePlatformPromotionTag\(item\.id, hasReferences\)/);
assert.match(dictionary, /deletingId\.value = item\.id/);
assert.match(dictionary, /deletingId === item\.id \? '删除中\.\.\.'/);
assert.match(dictionary, /系统保留运营标签，不能删除/);
assert.doesNotMatch(dictionary, /disablePlatformPromotionTag/);

assert.match(detail, /tag\.scope === 'OPERATIONAL'/);
assert.match(detail, /tag\.scope === 'CUISINE'/);
assert.match(detail, /tag\.scope === 'SCENE'/);
assert.match(detail, /运营标签（详情页 \+ 首页\/推荐）/);
assert.match(detail, /菜系与场景标签（详情页）/);
assert.match(detail, /显示在商家详情名称下方，并保留现有首页与推荐运营逻辑/);
assert.match(detail, /updatePlatformMerchantTags\(merchantId\.value, \[\.\.\.selectedTagIds\.value\]\)/);
assert.match(detail, /\+ 新增运营标签/);
assert.match(detail, /\+ 新增菜系/);
assert.match(detail, /\+ 新增场景/);
assert.match(detail, /openPromotionTagEdit\(tag\)/);
assert.match(detail, /removePromotionTag\(tag\)/);
assert.match(detail, /createPlatformPromotionTag\(payload\)/);
assert.match(detail, /updatePlatformPromotionTag\(current\.id, payload\)/);
assert.match(detail, /deletePlatformPromotionTag\(tag\.id, hasReferences\)/);
assert.match(detail, /新增后不会自动绑定当前商家/);
assert.match(detail, /现有商家关联保持不变/);
assert.match(detail, /系统标签/);
assert.match(detail, /该标签当前被 \$\{tag\.merchantReferenceCount\} 个商家使用/);
assert.match(detail, /请再次确认永久删除/);
assert.match(detail, /selectedTagIds\.value = selectedTagIds\.value\.filter/);
assert.match(api, /confirmReferenced = false/);
assert.match(api, /params: confirmReferenced \? \{ confirmReferenced: true \}/);
assert.match(detail, /type: 'STORE',[\s\S]*title: '门店外观'/);
assert.match(detail, /type: 'PRODUCT',[\s\S]*title: '菜品'/);
assert.match(detail, /type: 'ENVIRONMENT',[\s\S]*title: '用餐环境'/);
assert.match(detail, /type: 'MENU',[\s\S]*title: '菜单'/);
assert.match(detail, /小程序顶部图库：门店外观/);
assert.match(detail, /小程序顶部图库：菜品/);
assert.match(detail, /小程序顶部图库：用餐环境/);
assert.match(detail, /当前商家详情顶部图库不展示 MENU/);
assert.match(detail, /displayLimit: 3,[\s\S]*displayLimit: 6,[\s\S]*displayLimit: 3,/);
assert.match(detail, /const contentImageSections = computed/);
assert.match(detail, /visibleCount > section\.displayLimit/);
assert.match(detail, /frontendImagePositions/);
assert.match(detail, /前台第 \$\{section\.frontendImagePositions\[image\.id\]\} 张/);
assert.match(detail, /超出顶部图库展示上限/);
assert.match(detail, /v-for="section in contentImageSections"/);
assert.match(detail, /openImagePicker\(section\.type\)/);
assert.match(detail, /v-model\.number="image\.sortOrder"/);
assert.match(detail, /v-model="image\.isVisible"/);
assert.match(detail, /replacePlatformMerchantPrimaryImage/);
assert.match(detail, /replacePlatformMerchantImage/);
assert.match(detail, /uploadPlatformMerchantContentImage/);
assert.match(detail, /deletePlatformMerchantPrimaryImage/);
assert.match(detail, /deletePlatformMerchantImage/);
assert.match(detail, /替换图片会保持原分类、排序与展示状态/);
assert.match(detail, /删除后小程序对应图片会消失/);
assert.doesNotMatch(detail, /hidePlatformMerchantImage|hideMerchantImage\(image\)/);
assert.doesNotMatch(detail, /uploadPlatformMerchantImage\(file\)[\s\S]{0,300}createPlatformMerchantImage/);
assert.match(detail, /selectedCuisineTags/);
assert.match(detail, /selectedSceneTags/);
assert.match(detail, /frontendDetailTagIds/);
assert.match(detail, /超出前台上限/);
assert.match(detail, /messageIsSuccess/);
assert.match(detail, /aria-live="polite"/);
assert.doesNotMatch(detail, /<h3>内容图库<\/h3>/);
assert.match(list, /item\.enabled && item\.scope === 'OPERATIONAL'/);

console.log('promotion-tag-scope-ui: source assertions passed.');
